### ISSUE TITLE
Create a Checkbox component similar to MUI checkbox component using class bases css.

### ISSUE THREAD

**Issue by bhujoshi** [upnotes-io/react-todo#13]

**Comment by Avinier** [comment]
I will take this up👍

**Comment by Avinier** [comment]
@kamalkishor1991 @bhujoshi hi so y'all want the styles in a separate CSS file or how

**Comment by bhujoshi** [comment]
@Avinier We want to move out from the MUI component and want to write our component. So that we can remove MUI dependacy.
