### ISSUE TITLE
Add jest tests with github action to execute test on every PR and merge

### ISSUE THREAD

**Issue by kamalkishor1991** [upnotes-io/react-todo#23]
1. Introducing jest for testing scenario with writing few high level tests for each component. 
2. Adding github action to execute tests on each PR and merge.

**Comment by jisundr** [comment]
Hi @kamalkishor1991 i think this issue can break into smaller tasks. 

1. Setup the jest first.
2. Create a test per component.

What do you think?

**Comment by jisundr** [comment]
Let me work on this. I'll set up the jest and the github action

**Comment by jisundr** [comment]
Let me work on this. I'll set up the jest and the github action 

Do you want to include the lint on PR checks?
