### ISSUE TITLE
update on delete icon

### ISSUE THREAD

**Issue by AnasMansy** [upnotes-io/react-todo#28]
when hover on delete icon
![befor](https://user-images.githubusercontent.com/91702503/194311563-b5736078-3b9d-4505-819e-7f679dc66a5f.JPG)
change backgruond color to
![after](https://user-images.githubusercontent.com/91702503/194311616-f8b19e25-bf7b-4bf5-a954-005b40c45e8f.JPG)

can i work on this as my first conterpution

**Comment by kamalkishor1991** [comment]
@AnasMansy thanks. Can you make it circular on hover. Assigning it to you.

**Comment by AnasMansy** [comment]
what about this !
![edit111](https://user-images.githubusercontent.com/91702503/194617336-36ad47fa-e2d3-4585-99f9-7ea899264140.JPG)
i added bg color "#b9b5b5"
and padding "2px"

**Comment by kamalkishor1991** [comment]
yes this looks better.

**Comment by AnasMansy** [comment]
ok could you add label "hacktoberfest" to this issue please

**Comment by kamalkishor1991** [comment]
Thanks @AnasMansy 
https://github.com/upnotes-io/react-todo/pull/35
