### ISSUE TITLE
User should be able to navigate using up and down arrow keys in todo items.

### ISSUE THREAD

**Issue by bhujoshi** [upnotes-io/react-todo#30]

**Comment by serickson67** [comment]
I'd like to work on this, will you assign it to me?

**Comment by serickson67** [comment]
Thanks, I'm on it!

**Comment by serickson67** [comment]
Hi - I've made some good progress on this, but have some questions about how you would like certain cases to behave:

- Do you want the up arrow key to allow the cursor to move just between the created ToDoItems or should it also allow you to arrow up into the 'Add Item' text field?
- Do you want the up arrow/down arrow to be circular? Meaning, if the cursor is at the top of the list of items, and you hit the up arrow it will move the cursor to the bottom? And vice versa for the down arrow at the bottom of the list of items.

**Comment by serickson67** [comment]
Please review my pull request: #41

**Comment by serickson67** [comment]
Hey - I linked my pull request above, but it doesn't seem linked to this issue. Sorry, I'm fairly new to contributing to open-source projects, could you tell me how I should have linked it?

**Comment by serickson67** [comment]
Hey - please don't forget to review my pull request with the updates - and also, can you please add the hacktoberfest label to this issue and the pull request so I can get credit there? I appreciate it.

**Comment by kamalkishor1991** [comment]
@serickson67 thanks for helping out with this. Merged the PR and closed the ticket.
