### ISSUE TITLE
Handle pressing back in the beginning of the todo item

### ISSUE THREAD

**Issue by kamalkishor1991** [upnotes-io/react-todo#37]
Right now nothing happens if you press back in the beginning of the todo item.

1. If todo note is empty it should get deleted.
2. If the text size is greater than 0 it should merge into previous todo item

**Comment by samyakvaidya10** [comment]
Hi, can you assign this issue to me? I have previously worked on react and I can resolve this issue.

**Comment by Jayesh2812** [comment]
Hey, I see this issue isn't fixed yet.
Can I work on this issue ?

**Comment by kamalkishor1991** [comment]
@Jayesh2812 sure. You can work in it. Assigned it to you.

**Comment by Jayesh2812** [comment]
@kamalkishor1991 this issue is fixed in PR #46. Please have a look and review the changes.

**Comment by Param-Singh** [comment]
hey @kamalkishor1991 let me know if this issue is still open, I would love to work on this

**Comment by Param-Singh** [comment]
@kamalkishor1991 thanks,will close it by this weekend

**Comment by SamJHudson01** [comment]
Is this issue still open? I've literally just done this exact work in React for a personal shopping list app, so could get it done quickly
