### ISSUE TITLE
Add undo/redo support across items add and removal

### ISSUE THREAD

**Issue by kamalkishor1991** [upnotes-io/react-todo#38]
Ctr/cmd + z and ctr/cmd + y should work accross multiple items while undo and redo. Please refer to google keep behavier of undo  and redo for checkboxes.

**Comment by AnasMansy** [comment]
i want to work on this issue 
![Inkedredo](https://user-images.githubusercontent.com/91702503/194702717-8cc58aa8-97d7-485d-af44-87b180d4ede3.jpg)
is this what i should do ?

**Comment by kamalkishor1991** [comment]
@AnasMansy yes. You can also put buttons for it along with support for shortcuts. Assigning it to you.

**Comment by AnasMansy** [comment]
is this the expected ?

![redo1](https://user-images.githubusercontent.com/91702503/194710508-16456ab6-ab2f-4236-88d6-63f4a2d06b27.JPG)

**Comment by bhujoshi** [comment]
Hi @AnasMansy, This UI is distracting for user. For now, just implement undo/redo using shortcuts.

**Comment by AnasMansy** [comment]
@kamalkishor1991 @bhujoshi  i need help 
can you help me to know a way to implement undo redo

**Comment by kamalkishor1991** [comment]
@AnasMansy You can use undo and redo as a state and append into state once new item is added/removed and remove from state if undo is triggered.
For simplicity you can only implement undo first.
You can also refer to this question for reference
https://stackoverflow.com/questions/64963955/implementing-undo-redo-function-in-react

**Comment by AnasMansy** [comment]
hi @kamalkishor1991  could you check this i implemented undo and shortcut ctrl+z
`
  const handleKeyPress = (event:any) => {
   if(`${event.key}`=='z'&&`${event.key.control}` ) {
 
    setRedo([...redo,undo[0]])
    undo.splice(0, 1);  
    setItems(undo);
  }
  } ;

  useEffect(() => { 
    document.addEventListener('keydown', handleKeyPress);
 
    return () => {
      document.removeEventListener('keydown', handleKeyPress);
    };
  }, [handleKeyPress]);
   
`

**Comment by kamalkishor1991** [comment]
@AnasMansy can you please create a pull request with your changes?

**Comment by AnasMansy** [comment]
@kamalkishor1991 sure
sorry about that

**Comment by shahanahmed86** [comment]
I've created a [pull request](https://github.com/upnotes-io/react-todo/pull/56) which has the implementation of the required feature that is "ctrl+z" or "ctrl+y". [demo](https://github.com/upnotes-io/react-todo/assets/42711061/1e4229ad-3df5-456f-919f-e52509ff2fca)

**Comment by shahanahmed86** [comment]
@kamalkishor1991 This feature has already been done on the [pull request](https://github.com/upnotes-io/react-todo/pull/56), right?

**Comment by kamalkishor1991** [comment]
yes @shahanahmed86 
Thanks for reminding. Closing this issue now.
