### ISSUE TITLE
Drag and drop implementation needed to change todo list ordering 

### ISSUE THREAD

**Issue by bhujoshi** [upnotes-io/react-todo#4]
- User should be able to rearrange to-do items using drag and drop.

![ezgif-4-87a317711b](https://user-images.githubusercontent.com/9627563/193379183-28b945bc-56f3-42ff-9fbf-c10b367775cc.gif)

**Comment by eduSancho6** [comment]
Hello, can i help with this issue?

**Comment by bhujoshi** [comment]
@eduSancho6 Thanks, Sure it would be great. Let me know in case you need any help from me. You can also join our discord  channel ( https://discord.gg/ATZTMeyWsW ) and ping me over there.

**Comment by mkirvan00** [comment]
Hello! I believe I have successfully implemented this feature. How should I go about incorporating it into the repo?

**Comment by bhujoshi** [comment]
Thanks @mkirvan00 I am reviewing the PR. Will update you

**Comment by jisundr** [comment]
Any update on this?

**Comment by bhujoshi** [comment]
@jisundr this is still open. If you want to take this up just add a comment working on this.

**Comment by jisundr** [comment]
Got it. I'll look into the code first. Thanks.

**Comment by jisundr** [comment]
@bhujoshi I'll take this task. please assign this to me. Thanks.

**Comment by jisundr** [comment]
Hi @bhujoshi, It seems the `Todo.tsx` is composed of multiple components. And it's to read it. I wonder if I could separate this on smaller components?

**Comment by jisundr** [comment]
Hi @bhujoshi let me know if this issue needs to be closed. Thanks.

**Comment by kamalkishor1991** [comment]
@jisundr thanks for implementing this. Closing 
PR: #21
