### ISSUE TITLE
require more accurate instruction for Contributor guided

### ISSUE THREAD

**Issue by Curis-lab** [upnotes-io/react-todo#60]
I have setup the following instruction but I got some errors like this
```
warning package.json: "dependencies" has dependency "husky" with range "^8.0.3" that collides with a dependency in "devDependencies" of the same name with version "^8.0.0"
warning react-todo-component@2.2.1: "dependencies" has dependency "husky" with range "^8.0.3" that collides with a dependency in "devDependencies" of the same name with version "^8.0.0"
..
```
I don't know how to solve it.

**Comment by kamalkishor1991** [comment]
@Curis-lab this is just a warning so you can just ignore it also. Thanks for reporting it
I fixed it [here](https://github.com/upnotes-io/react-todo/commit/56c68cc66cc350740d85379f03660df6ad427bb8) 
Please pull the latest master.
